export const STATES = [
  {
    id: 'anxious',
    label: 'Anxious or Worried',
    icon: '😰',
    description: 'Mind racing, chest tight, anticipating something bad.',
    dotColor: '#6B8FA3',
    dotBg: 'bg-ocean',
    recommendation: {
      text: 'The breathing pacer can slow your heart rate and ease that racing feeling.',
      toolSlug: 'breathing-exercise',
      toolLabel: 'Try the Breathing Pacer',
    },
  },
  {
    id: 'overwhelmed',
    label: 'Overwhelmed',
    icon: '😵',
    description: 'Too much at once, hard to think, everything feels heavy.',
    dotColor: '#C4A484',
    dotBg: 'bg-clay',
    recommendation: {
      text: 'The 5-4-3-2-1 grounding technique will anchor you to the present, one sense at a time.',
      toolSlug: 'grounding-54321',
      toolLabel: 'Try 5-4-3-2-1 Grounding',
    },
  },
  {
    id: 'numb',
    label: 'Numb or Disconnected',
    icon: '😶',
    description: 'Zoned out, flat, not feeling much, hard to connect.',
    dotColor: '#8A8A8A',
    dotBg: 'bg-charcoal/50',
    recommendation: {
      text: 'The orienting exercise can gently bring you back into your body and the room around you.',
      toolSlug: 'orienting',
      toolLabel: 'Try Orienting',
    },
  },
  {
    id: 'restless',
    label: 'Restless or Agitated',
    icon: '😤',
    description: 'Fidgety, irritable, can\'t settle, energy with nowhere to go.',
    dotColor: '#E07A6A',
    dotBg: 'bg-sos',
    recommendation: {
      text: 'Shake It Off gives that restless energy somewhere to go — through your body and out.',
      toolSlug: 'shake-it-off',
      toolLabel: 'Try Shake It Off',
    },
  },
  {
    id: 'tired',
    label: 'Tired or Drained',
    icon: '😴',
    description: 'Low energy, heavy, need to rest but can\'t fully switch off.',
    dotColor: '#A8C4BB',
    dotBg: 'bg-sage/60',
    recommendation: {
      text: 'A gentle body scan can help you release held tension and ease your way toward rest.',
      toolSlug: 'body-scan',
      toolLabel: 'Try the Body Scan',
    },
  },
  {
    id: 'calm',
    label: 'Calm or Grounded',
    icon: '😌',
    description: 'Feeling present, steady, and at ease. Good moment to build resilience.',
    dotColor: '#7C9A8E',
    dotBg: 'bg-sage',
    recommendation: {
      text: 'Great. When you\'re calm is the best time to build your inner resources. Try pendulation or resourcing.',
      toolSlug: 'pendulation',
      toolLabel: 'Try Pendulation',
    },
  },
]
